config/routes.rb
Rails.application.routes.draw do
  root to: 'public/home#show'

  devise_for :admins,
    controllers: {
      sessions:           'admin/authentication/sessions',
      passwords:          'admin/authentication/passwords'
    }

  namespace :public, path: '/' do
    resources :home, path: '', only: [:show]
  end

  namespace :admin do
    resources :categories
  end

end

app/models/admin.rb
# encoding: utf-8
class Admin < ActiveRecord::Base

  # devise
  devise :database_authenticatable, :validatable, :recoverable, :rememberable

  # validations
  validates :name, presence: true
  validates :email, presence: true

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/admin/authentication/passwords_controller.rb
# encoding: utf-8
class Admin::Authentication::PasswordsController < ::Devise::PasswordsController
  layout 'login'

  def after_resetting_password_path_for(admin)
    admin_categories_path
  end

end

app/controllers/admin/authentication/sessions_controller.rb
# encoding: utf-8
class Admin::Authentication::SessionsController < ::Devise::SessionsController
  layout 'login'

  def after_sign_in_path_for(admin)
    admin_categories_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end

end

app/controllers/admin/base_controller.rb
# encoding: utf-8
class Admin::BaseController < ApplicationController
  protect_from_forgery
  layout 'admin/main'
  before_filter :authenticate_admin!
  respond_to :html
  responders :flash
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create(permitted_params)
    respond_with(@category, location: admin_categories_path)
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(permitted_params)
    respond_with(@category, location: admin_category_path)
  end

  def show
    @category = Category.find(params[:id])
    respond_with @category
  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_with(@category, location: admin_categories_path)
  end


  private
    def permitted_params
      params.require(:category).permit!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/base_helper.rb
# encoding: utf-8

module Admin::BaseHelper
  include Shared::CodusTemplateHomer
  include Shared::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Shared::IconsHelper
  include Shared::CodusTemplateHomer::Base
end

app/helpers/shared/base_helper.rb
# encoding: utf-8
module Shared::BaseHelper
  include Shared::IconsHelper
end

app/helpers/shared/codus_template_homer/base.rb
# encoding: utf-8

module Shared::CodusTemplateHomer
  module Base
    include CodusTemplates::Helpers::Base

    def menu_active_for(sym, actions = nil)
      super(sym, actions).gsub("open", "")
    end

    def display_flash_message
      return if flash.empty?
      alerts = flash.inject('') do |content, (key, message)|
        next unless [:alert, :success, :notice, :error, :danger, :warning, :info].include?(key.to_sym)
        key = :success if key.to_sym == :notice
        key = :danger if key.to_sym.in? [:error, :alert]

        alert = content_tag :div, :class => "alert alert-#{key}" do
          content_tag(:p, message) unless message.blank?  || key.to_sym == :timedout
        end.html_safe
        content << alert.html_safe
      end
      alerts.html_safe if alerts
    end

    def header_section(custom_options = {})
      options = {
        title: get_title_text_for_header_section,
        right_links: get_right_links_for_header_section,
        header_tag: :h2
      }.merge(custom_options)

        # .hpanel
        #   .panel-body
        #     h2 .font-light.m-b-xs
        #       | Forms elements

      content_tag(:div, class: 'normalheader transition animated fadeIn') do
        content_tag(:div, class: 'hpanel') do
          content_tag(:div, class: 'panel-body') do
            title = content_tag(options[:header_tag], "#{options[:title]}".html_safe, class: "font-light m-b-xs")
            (title).html_safe
          end
        end
      end
    end

    def get_right_links_for_header_section
      begin
        right_links = link_to(get_translation_for_button(:back), {action: 'index'}, {class: 'btn btn-default'})
      rescue
        right_links = ""
      end
      if params[:action].match(/index/)
        begin
          right_links = link_to("#{get_translation_for_button(:add)}".html_safe, { action: :new }, class: 'btn btn-primary cpy-add-link')
        rescue
          right_links = ""
        end
      end

      right_links
    end

    def form_submit_section(custom_options = {})
      options = {
        back_button_name: get_translation_for_button(:back),
        submit_button_name: get_translation_for_button(:save)
      }.merge(custom_options)
      content_tag(:div, class: 'form-group') do
        content_tag(:div, class: 'col-sm-8 col-sm-offset-2') do
          begin
            back_link = link_to("#{options[:back_button_name]}".html_safe, {action: 'index'}, {class: 'btn btn-default'})
          rescue
            back_link = link_to("#{options[:back_button_name]}".html_safe, :back, {class: 'btn btn-default'})
          end
          submit_button = "<button class='btn btn-primary cpy-submit-button'> #{options[:submit_button_name]}</button> ".html_safe
          (submit_button + back_link).html_safe
        end
      end
    end

    def show_buttons_section(custom_options = {})
      options = {
        back_button_name: get_translation_for_button(:back),
        edit_button_name: get_translation_for_button(:edit)
      }.merge(custom_options)

      buttons = content_tag(:div, class: 'form-group') do
        content_tag(:div, class: 'col-sm-8 col-sm-offset-2') do
          if options[:path_to_return]
            back_link = link_to("#{options[:back_button_name]}".html_safe, options[:path_to_return].to_sym, {class: 'btn btn-default'})
          else
            begin
              back_link = link_to("#{options[:back_button_name]}".html_safe, {action: 'index'}, {class: 'btn btn-default'})
            rescue
              back_link = link_to("#{options[:back_button_name]}".html_safe, :back, {class: 'btn btn-default'})
            end
          end
          begin
            edit_link = link_to("#{options[:edit_button_name]}".html_safe, {action: 'edit'}, {class: 'btn btn-primary'})
          rescue
            edit_link = ''
          end

          begin
            edit_link = link_to("#{options[:edit_button_name]}".html_safe, {action: 'edit'}, {class: 'btn btn-primary'})
          rescue
            edit_link = ''
          end

          back_link + edit_link
        end
      end
      buttons.html_safe
    end

    def date_input(options)
      f = options.delete(:form_builder)
      attribute = options.delete(:attribute)
      input_options = {
        as: :string
      }.merge(options.fetch(:input_options, {}))
      input_options[:class] = "form-control js-mask-date #{input_options[:class].to_s}"
      extra_options = {}
      if options.has_key?(:wrapper)
        extra_options[:wrapper] = options[:wrapper]
      end

      f.input(attribute, extra_options) do
        content_tag(:div, class: 'input-group date') do
          input_options[:value] = f.object.send(attribute).nil? ? '' : I18n.l(f.object.send(attribute), format: '%d/%m/%Y')
          input = f.input_field(attribute, input_options)
          calendar_icon = content_tag(:span, class: 'input-group-addon') do
            content_tag(:i, '', { class: 'glyphicon glyphicon-th'} )
          end
          input + calendar_icon
        end
      end
    end

    def pagination_themed(resource_list, options = {})
      final_options = {
        :theme => 'ace_template'
      }.merge(options)
      paginate(resource_list, final_options)
    end
  end
end

app/helpers/shared/icons_helper.rb
module Shared::IconsHelper
  def icon_for(icon_type)
    selected_icon_class = Hash.new {|hash, key| hash[key] = "fa fa-#{key}" }
    selected_icon_class.merge(
      show: 'fa fa-eye',
      edit: 'fa fa-pencil',
      plus: 'fa fa-plus',
      back: 'fa fa-arrow-left',
      question: 'fa fa-question-circle',
      user: 'pe-7s-user',
      mail: 'pe-7s-mail',
      signout: 'sign-out'
    )
    "<i class='#{selected_icon_class[icon_type]}'></i>".html_safe
  end
end

app/views/admin/categories/_form.html.slim
= f.input :name

= form_submit_section

app/views/admin/categories/edit.html.slim
.hpanel
  .panel-body
    h2.font-light.m-b-xs
      | Editando categoria
= simple_form_for [:admin, @category] do |f|
  = render partial: 'form', locals: {f: f}

app/views/admin/categories/index.html.slim
.hpanel
  .panel-body
    h2.font-light.m-b-xs
      | Listando Categorias
      = link_to "Adicionar", new_admin_category_path, class: 'pull-right btn btn-md btn-success'

.ibox
  .ibox-content
    - if @categories.any?
      .cpy-pagination-wrapper
        = pagination_themed(@categories)
        table.table.table-bordered.table-hover.table-striped.cpy-table
          thead
            th ID
            th Nome
            th
          tbody
            - @categories.each do |category|
              tr.cpy-line-course
                td = category.id
                td = category.name
                td.text-center
                  = link_to(admin_category_path(category.id), class: 'btn btn-xs btn-success') do
                    | Mostrar
                  | &nbsp;
                  = link_to(edit_admin_category_path(category.id), class: 'btn btn-xs btn-warning') do
                    | Editar
                  | &nbsp;

                  = link_to(admin_category_path(category.id), class: 'btn btn-xs btn-danger', method: :delete, 'data-confirm' => 'Deseja mesmo remover a categoria?') do
                    | Remover

        = pagination_themed(@categories)

    - else
      .alert.alert-info
        | Não existe nenhuma Categoria cadastrada.&nbsp;
        = link_to "Clique aqui para adicionar uma categoria", new_admin_category_path

app/views/admin/categories/new.html.slim
.hpanel
  .panel-body
    h2.font-light.m-b-xs
      | Adicionando categoria
= simple_form_for [:admin, @category] do |f|
  = render partial: 'form', locals: {f: f}

app/views/admin/categories/show.html.slim
.hpanel
  .panel-body
    h2.font-light.m-b-xs
      | Detalhes categoria
.ibox.ibox-double-padding
  .ibox-content
    = show_for @category do |sf|
      = sf.attribute :id
      = sf.attribute :name
    = show_buttons_section

app/views/layouts/admin/main.html.slim
| <!DOCTYPE html>
html
  head
    = stylesheet_link_tag    'homer/init', media: 'all'
    = javascript_include_tag 'init_admin', media: 'all'
    = csrf_meta_tags

  body.pace-done.cpy-logged-pannel class="#{classes_for_scoped_css}"
    .splash
      .color-line
        .splash-title
          h1 Codus Store
    #header
      #logo.light-version
        span
          | Codus Store
      nav role="navigation"
        .small-logo
          .text-primary Codus Store
        .navbar-right
          ul.nav.navbar-nav.no-borders

            li.dropdown
              a class="dropdown-toggle" href="#" data-toggle="dropdown"
                = icon_for :user
              ul class="dropdown-menu hdropdown notification animated flipInX"
                li
                  = link_to '3' do
                    span.label.label-success
                      | Mostrar
                    | Associações
                li
                  = link_to '3' do
                    span.label.label-danger
                      | Deletar
                    | Associações
                li
                  = link_to destroy_admin_session_path, method: :delete do
                    = icon_for :signout
                    |  Sair

    .small-header.transition.animated.fadeIn
      .hpanel
        ul.list-inline.top-menu.clearfix
          li
            = link_to admin_categories_path do
              = icon_for(:category)
              span Categorias
          li
            = link_to destroy_admin_session_path, method: :delete do
              span Logout
    #wrapper
      = display_flash_message
      .content
        = yield
    .panel-footer
      .col-sm-12.text-center
        | Codus Store

app/views/layouts/email.html.slim
head
  css:
    #outlook a {padding:0;}
    body {width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
    .ExternalClass {width:100%;}
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
    #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
    img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
    a img {border:none;}
    .image_fix {display:block;}
    p {margin: 1em 0;}
    h1, h2, h3, h4, h5, h6 {color: black !important;}
    h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}
    h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
        color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
    }
    h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
        color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
    }
    table td {border-collapse: collapse;}
    table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
    a {color: orange;}
    a:link { color: orange; }
    a:visited { color: blue; }
    a:hover { color: green; }
    td.button {
      vertical-align: middle;
      text-align: center;
      background: #0163ac;
      border-radius: 5px;
    }
    td.button a {
      display: block;
      color: #ffffff !important;
      padding: 15px 0;
      cursor: pointer;
      text-decoration: underline;
    }
    h2 {
      color: #1AB394 !important;
      text-transform: uppercase;
      font-weight: lighter;
    }
    td.reset-pw-txt p {
      font-family:  'Helvetica Neue', Helvetica, Arial;
      font-size: 15px;
      color: #676A6C;
    }

    .btn-success {
      background-color: #62cb31;
      border-color: #62cb31;
      color: #FFFFFF;
      text-decoration: none !important;
    }


body style="background: #f4f7f9; font-family:Helvetica Neue, Helvetica, Arial;"
  table#backgroundTable align="center" bgcolor="#f4f7f9" border="0" cellpadding="0" cellspacing="0" style="background: #f4f7f9; font-family:Helvetica Neue, Helvetica, Arial;" width="100%"
    tr
      td align="center"
        center
          table border="0" cellpadding="50" cellspacing="0" style="margin-left: auto;margin-right: auto;width:600px;text-align:center;" width="600"
            tr
              td align="center" valign="top"
                h1 Codus Logo
                / = image_tag(image_url('logo.gif'), style: "outline:none; text-decoration:none;border:none,display:block;")
    tr
      td align="center"
        center
          table border="0" cellpadding="30" cellspacing="0" style="margin-left: auto;margin-right: auto;width:600px;text-align:center;" width="600"
            tr
              td align="left" style="background: #ffffff; border: 1px solid #dce1e5;" valign="top" width=""
                table border="0" cellpadding="0" cellspacing="0" width="100%"
                  tr
                    td align="center" valign="top"
                      h2 = yield(:title)
                  tr
                    td align="center" valign="top"
                      h4 style="color: #f34541 !important" = yield(:subtitle)
                  = yield

app/views/layouts/login.html.slim
| <!DOCTYPE html>
html
  head
    = stylesheet_link_tag    'homer/init', media: 'all'
    = javascript_include_tag 'init_company', media: 'all'
    = csrf_meta_tags

  body.blank
    .login-container
      .row
        .col-md-12
          .text-center.m-d-md
            h3 Codus Store
          .hpanel
            = display_flash_message
            = yield